site_name: TRAINING WIKI
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: ru
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Тёмная тема
      primary: orange
      accent: orange
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Светлая тема
      primary: orange
      accent: orange

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  mkdocs-video:
    is_video: True
    css_style:
      height: "25vw"
